global:
  resolve_timeout: 1m   # 실 운영
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  group_by: ['alertname', 'status', 'uri']
  group_wait: 0s          # 알림 딜레이 없이 바로 전송 | 운영 ) 5s
  group_interval: 5s      # 운영) 30s
  repeat_interval: 1m     # 동일 조건이면 1분 뒤 재전송 | 운영) 5m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#웹백엔드-5-04차team-07팀'
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'

# 적용 후 재시작 필수: docker-compose restart prometheus alertmanager
# 항목 확인 경로) 	http://localhost:9090/alerts
# Alert 발동 상태 확인 경로)   http://localhost:9093