import os, time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

EMAIL    = os.environ["YT_EMAIL"]
PASSWORD = os.environ["YT_PASSWORD"]
OUT_PATH = os.environ.get("YT_COOKIES_PATH", "/tmp/cookies.txt")

opts = Options()
opts.add_argument("--headless")
opts.add_argument("--no-sandbox")
opts.add_argument("--disable-dev-shm-usage")
opts.add_argument("--disable-gpu")
opts.add_argument("--window-size=1920,1080")

driver = webdriver.Chrome(options=opts)
try:
    driver.get("https://accounts.google.com/signin/v2/identifier?service=youtube")
    time.sleep(5)
    driver.find_element("css selector", "input[type='email']").send_keys(EMAIL)
    driver.find_element("id", "identifierNext").click()
    time.sleep(10)
    driver.find_element("css selector", "input[type='password']").send_keys(PASSWORD)
    driver.find_element("id", "passwordNext").click()
    time.sleep(10)
    driver.get("https://www.youtube.com")
    time.sleep(10)

    cookies = driver.get_cookies()
    with open(OUT_PATH, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by save_headless_cookies.py\n\n")
        for c in cookies:
            domain = c["domain"]
            if c.get("httpOnly"):
                domain = "#HttpOnly_" + (domain if domain.startswith(".") else "."+domain)
            include_subdomains = "TRUE" if c["domain"].startswith(".") else "FALSE"
            path    = c["path"]
            secure  = "TRUE" if c.get("secure") else "FALSE"
            expires = str(int(c.get("expiry",0)))
            name    = c["name"]
            value   = c["value"]
            f.write("\t".join([domain, include_subdomains, path, secure, expires, name, value]) + "\n")
    print(f"[+] Saved {len(cookies)} cookies to {OUT_PATH}")
finally:
    driver.quit()
