INSERT INTO PUBLIC.SUBTITLE (END_TIME,ORIGINAL_SENTENCE,SPEAKER,START_TIME,TRANSLATED_SENTENCE,VIDEO_ID) VALUES
                                                                                                             ('00:00:08.254','Hey everyone, welcome back to Van A Itch Dream Channel. If you''re passionate about technology and creativity, you''re in the right place.','A','00:00:00.000','안녕하세요 여러분, Van A Itch Dream Channel에 돌아오신 것을 환영합니다. 기술과 창의력에 열정이 있다면, 당신은 올바른 장소에 있습니다.','OGz4EJIUPiA'),
                                                                                                             ('00:00:16.000','Today we''re diving into the fascinating world of text to video AI generators. Stick around because you won''t want to miss this.','A','00:00:08.254','오늘 우리는 텍스트를 비디오로 변환하는 AI 생성기의 매혹적인 세계로 뛰어듭니다. 머물러 보세요, 이걸 놓치고 싶지 않을 겁니다.','OGz4EJIUPiA'),
                                                                                                             ('00:00:24.869','So what exactly is a Text to video AI generator? In simple terms it''s a tool that transforms written text into engaging video content.','A','00:00:16.000','그러면 텍스트를 비디오로 변환하는 AI 생성기란 정확히 무엇일까요? 간단히 말하면, 이는 작성된 텍스트를 매력적인 비디오 콘텐츠로 변환하는 도구입니다.','OGz4EJIUPiA'),
                                                                                                             ('00:00:33.080','You provide a script and the AI does the rest creating visuals, adding animations, and even incorporating background music.','A','00:00:24.869','당신이 스크립트를 제공하면 AI가 나머지를 처리하며, 시각 자료를 만들고, 애니메이션을 추가하며, 심지어 배경 음악도 통합합니다.','OGz4EJIUPiA'),
                                                                                                             ('00:00:43.080','Imagine being able to turn your ideas into videos without any video editing skills sounds amazing, right? Let''s explore how this technology works.','A','00:00:33.080','영상 편집 기술 없이도 아이디어를 비디오로 전환할 수 있다고 상상해 보세요. 놀랍지 않나요? 이 기술이 어떻게 작동하는지 알아봅시다.','OGz4EJIUPiA'),
                                                                                                             ('00:00:52.485','These AI tools use natural language processing and machine learning algorithms to analyze your text. They understand context, emotion and tone,','A','00:00:43.080','이러한 AI 도구들은 자연어 처리와 기계 학습 알고리즘을 사용하여 당신의 텍스트를 분석합니다. 그들은 문맥, 감정 및 어조를 이해합니다.','OGz4EJIUPiA'),
                                                                                                             ('00:00:58.885','allowing them to generate relevant images. And let''s dive in and explore how to use Video Gin effectively.','A','00:00:52.485','그들이 관련 있는 이미지를 생성하도록 합니다. 이제 Video Gin을 효과적으로 사용하는 방법을 깊이 탐구해 봅시다.','OGz4EJIUPiA'),
                                                                                                             ('00:01:09.354','First, you need to note that Video Gen is a paid tool and it offers different service packages such as the Pro Plann Scale Plan and Business plan. For most content creators,','A','00:00:58.885','우선 Video Gen이 유료 도구라는 것을 알아두어야 하며, Pro 플랜, Scale 플랜 및 비즈니스 플랜과 같은 다양한 서비스 패키지를 제공합니다. 대부분의 콘텐츠 제작자에게는,','OGz4EJIUPiA'),
                                                                                                             ('00:01:17.515','the pro Plan is enough to leverage its powerful features. If you subscribe annually, the average cost is about 16 dollars per month','A','00:01:09.354','프로 플랜만으로도 강력한 기능을 활용하기에 충분합니다. 연간 구독 시 평균 비용은 월 약 16달러입니다','OGz4EJIUPiA'),
                                                                                                             ('00:01:27.044','but if you pay monthly it''s 24 dollars. You''ll receive 60 A I credits per month, which is equivalent to about 60 minutes of video creation.','A','00:01:17.515','월별 결제 시 24달러입니다. 매월 60 AI 크레딧을 받게 되며, 이는 약 60분의 비디오 제작에 해당합니다.','OGz4EJIUPiA');
INSERT INTO PUBLIC.SUBTITLE (END_TIME,ORIGINAL_SENTENCE,SPEAKER,START_TIME,TRANSLATED_SENTENCE,VIDEO_ID) VALUES
                                                                                                             ('00:01:35.595','If you make five minute videos, you can produce around 12 videos per month. For comparison, hiring a video editor to produce a five minute video','A','00:01:27.044','만약 5분짜리 비디오를 제작한다면, 한 달에 약 12개의 비디오를 제작할 수 있습니다. 비교해보면, 5분짜리 비디오를 제작하기 위해 비디오 편집자를 고용하면','OGz4EJIUPiA'),
                                                                                                             ('00:01:43.544','including editing would cost you around 24 dollars, which is almost the same as the price of using Video Gen for an entire month.','A','00:01:35.595','편집을 포함하면 약 24달러가 들며, 이는 Video Gen을 한 달 동안 사용하는 비용과 거의 동일합니다.','OGz4EJIUPiA'),
                                                                                                             ('00:01:51.350','Meanwhile, Video is very easy to use and supports multiple platforms. To sign up for an account, simply click Sign up,','A','00:01:43.544','한편 Video는 사용이 매우 쉽고 여러 플랫폼을 지원합니다. 계정을 등록하려면 간단히 가입을 클릭하세요,','OGz4EJIUPiA'),
                                                                                                             ('00:02:01.065','fill in your personal details and you''re ready to go. I''ve included the registration link in the video description below. Once logged in and upgraded to a paid plan,','A','00:01:51.350','개인 정보를 입력하면 시작할 준비가 됩니다. 아래 비디오 설명에 등록 링크를 포함했습니다. 로그인하고 유료 플랜으로 업그레이드하면,','OGz4EJIUPiA'),
                                                                                                             ('00:02:08.610','the working interface will look like this. Completed projects will appear in the recent video section. If you don''t have any videos yet,','A','00:02:01.065','작업 인터페이스는 이렇게 보입니다. 완료된 프로젝트는 최근 비디오 섹션에 나타납니다. 아직 비디오가 없다면,','OGz4EJIUPiA'),
                                                                                                             ('00:02:15.704','this section will be empty. The Video Gen interface only has a few main menus and I''ll guide you through each part.','A','00:02:08.610','이 섹션은 비어 있을 것입니다. Video Gen 인터페이스에는 몇 가지 주요 메뉴만 있으며 각 부분을 안내해 드리겠습니다.','OGz4EJIUPiA'),
                                                                                                             ('00:02:22.790','The main feature of Video Jen is creating videos that can be shared across multiple platforms. To get started,','A','00:02:15.704','Video Jen의 주요 기능은 여러 플랫폼에서 공유할 수 있는 비디오를 만드는 것입니다. 시작하려면,','OGz4EJIUPiA'),
                                                                                                             ('00:02:31.985','click Generate a video you''ll see a selection of video templates based on the platform you want to use such as YouTube, TikTok, or Instagram.','A','00:02:22.790','당신이 사용하고자 하는 플랫폼에 기반한 비디오 템플릿의 선택을 보려면 비디오 생성하기를 클릭하세요. 예: YouTube, TikTok 또는 Instagram.','OGz4EJIUPiA'),
                                                                                                             ('00:02:42.195','Each template will have a free or pro label depending on your subscription plan. Let''s say you want to create a short video for TikTok. First select TikTok in the outline','A','00:02:31.985','각 템플릿에는 구독 플랜에 따라 무료 또는 프로 레이블이 붙습니다. TikTok용 짧은 비디오를 만들고 싶다면 먼저 아웃라인에서 TikTok을 선택하세요','OGz4EJIUPiA'),
                                                                                                             ('00:02:49.305','your video section enter information such as Create a product promotion video for men''s polo shirts for ages 25 to 40.','A','00:02:42.195','비디오 섹션에 "25세에서 40세 남성용 폴로 셔츠 홍보 비디오 생성"과 같은 정보를 입력하세요.','OGz4EJIUPiA');
INSERT INTO PUBLIC.SUBTITLE (END_TIME,ORIGINAL_SENTENCE,SPEAKER,START_TIME,TRANSLATED_SENTENCE,VIDEO_ID) VALUES
                                                                                                             ('00:02:56.660','After entering the details, you can select the script language, set the video length, say around 300 words for a medium-length video, click','A','00:02:49.305','세부 정보를 입력한 후, 스크립트 언어를 선택하고, 비디오 길이를 설정하세요. 중간 길이의 비디오는 약 300단어입니다, 클릭하세요','OGz4EJIUPiA'),
                                                                                                             ('00:03:00.965','Create Script and in just a few seconds a script will be generated for you.','A','00:02:56.660','스크립트 생성하기를 클릭하면 단 몇 초 만에 스크립트가 생성됩니다.','OGz4EJIUPiA'),
                                                                                                             ('00:03:07.430','What''s special is that the script generated by Video Gen sounds more natural and engaging than many other AI tools.','A','00:03:00.965','Video Gen이 생성한 스크립트는 다른 많은 AI 도구보다 더 자연스럽고 매력적으로 들리는 것이 특징입니다.','OGz4EJIUPiA'),
                                                                                                             ('00:03:16.370','When you''re satisfied with the script, you can choose the voice, male or female, in the appropriate language. After selecting the voice clip, continue for TikTok videos','A','00:03:07.430','스크립트에 만족하면 적절한 언어로 남성 또는 여성 목소리를 선택할 수 있습니다. 음성 클립을 선택한 후 TikTok 비디오를 계속 제작하세요','OGz4EJIUPiA'),
                                                                                                             ('00:03:29.000','video Gen automatically sets the vertical format, but you can also adjust the transition speed between scenes according to the style you want. Faster for dynamic video videos or slower for more relaxed ones.','A','00:03:16.370','Video Gen은 자동으로 세로 형식을 설정하지만, 원하는 스타일에 따라 장면 간 전환 속도를 조정할 수도 있습니다. 더 역동적인 비디오에는 빠르게, 더 편안한 비디오에는 느리게 설정하세요.','OGz4EJIUPiA'),
                                                                                                             ('00:03:36.035','Once everything looks good, click Create Video and Video Gen will automatically find suitable illustrative clips.','A','00:03:29.000','모든 것이 좋아 보이면 비디오 생성하기를 클릭하십시오, 그러면 Video Gen은 적절한 설명 클립을 자동으로 찾습니다.','OGz4EJIUPiA'),
                                                                                                             ('00:03:44.500','If you want to personalize the video with your own clips or images, just click the Upload icon to replace the default scenes with your product footage.','A','00:03:36.035','자신의 클립이나 이미지를 사용하여 비디오를 개인화하고 싶다면 업로드 아이콘을 클릭하여 기본 장면을 자신의 제품 영상으로 교체하세요.','OGz4EJIUPiA'),
                                                                                                             ('00:03:53.595','This is an easy way to make your video more unique. After editing and feeling satisfied with the video, you can download it in 1080P or 4K.','A','00:03:44.500','이것은 비디오를 더 독특하게 만드는 쉬운 방법입니다. 편집 후 비디오에 만족하면 1080P 또는 4K로 다운로드할 수 있습니다.','OGz4EJIUPiA'),
                                                                                                             ('00:04:01.195','If you''re excited to start creating with text to video AI generators, check out the links in the description for more resources.','A','00:03:53.595','텍스트를 비디오로 변환하는 AI 생성기를 사용하여 창작을 시작하고 싶다면, 설명에 기재된 링크를 확인하여 더 많은 자료를 찾아보세요.','OGz4EJIUPiA'),
                                                                                                             ('00:04:10.220','Don''t forget to like, subscribe and hit that notification bell for more Tech insights from Van AI Tech Dream Channel until next time.','A','00:04:01.195','더 많은 기술 인사이트를 위해 Van AI Tech Dream Channel을 좋아요, 구독하고 알림을 설정하는 것을 잊지 마세요. 다음 시간까지,','OGz4EJIUPiA');
INSERT INTO PUBLIC.SUBTITLE (END_TIME,ORIGINAL_SENTENCE,SPEAKER,START_TIME,TRANSLATED_SENTENCE,VIDEO_ID) VALUES
    ('00:04:12.080','Keep dreaming and creating.','A','00:04:10.220','꿈꾸고 창작하세요.','OGz4EJIUPiA');