INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','Creativity is essential for innovation.','창의성','명사','창의성은 혁신에 필수적이다.','creativity'),
                                                                                               ('HARD','The movie was absolutely fascinating.','매혹적인','형용사','그 영화는 정말로 매혹적이었다.','fascinating'),
                                                                                               ('NORMAL','She is passionate about art.','열정적인','형용사','그녀는 예술에 열정적이다.','passionate'),
                                                                                               ('HARD','She decided to dive into the pool.','뛰어들다','동사','그녀는 수영장에 뛰어들기로 결정했다.','dive into'),
                                                                                               ('HARD','He likes to dive into his work.','몰두하다','동사','그는 자신의 일에 몰두하는 것을 좋아한다.','dive into'),
                                                                                               ('NORMAL','He used a tool to fix the bike.','도구','명사','그는 자전거를 고치는 데 도구를 사용했다.','tool'),
                                                                                               ('HARD','The caterpillar will transform into a butterfly.','변형하다','동사','애벌레는 나비로 변형될 것이다.','transform'),
                                                                                               ('VERY_HARD','The transform of this equation simplifies the solution.','변환','명사','이 방정식의 변환은 해를 단순화한다.','transform'),
                                                                                               ('HARD','The actor can transform into different characters easily.','변신하다','동사','배우는 다양한 인물로 쉽게 변신할 수 있다.','transform'),
                                                                                               ('HARD','She has an engaging smile that lights up the room.','매력적인','형용사','그녀는 방을 환하게 밝히는 매력적인 미소를 지니고 있다.','engaging');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('VERY_HARD','The teacher was engaging the students in a lively discussion.','참여시키다','동사','교사는 학생들을 활발한 토론에 참여시키고 있었다.','engaging'),
                                                                                               ('NORMAL','There was a miss in the calculations.','실수','명사','계산에 실수가 있었다.','miss'),
                                                                                               ('NORMAL','Don''t miss the train.','놓치다','동사','기차를 놓치지 마세요.','miss'),
                                                                                               ('EASY','She won the title of Miss Universe.','미스','명사','그녀는 미스 유니버스 타이틀을 차지했다.','miss'),
                                                                                               ('HARD','I miss my hometown.','그리워하다','동사','나는 고향이 그립다.','miss'),
                                                                                               ('EASY','The teacher gave a warm welcome back to all students.','환영','명사','선생님은 모든 학생들을 따뜻하게 환영했다.','welcome back'),
                                                                                               ('NORMAL','We welcome back our friend with open arms.','환영하다','동사','우리는 친구를 따뜻이 환영한다.','welcome back'),
                                                                                               ('NORMAL','It is a welcome back sight to see the flowers blooming again.','반가운','형용사','꽃이 다시 피는 모습을 보는 것은 반가운 광경이다.','welcome back'),
                                                                                               ('HARD','He smiled, welcome back as if he''d been waiting.','다시 환영하며','부사','그는 기다렸던 것처럼 미소를 지으며, 다시 환영하며 말했다.','welcome back'),
                                                                                               ('NORMAL','The project will provide new jobs.','제공하다','동사','그 프로젝트는 새로운 일자리를 제공할 것이다.','provide');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','The hotel can provide all your meals.','준비하다','동사','그 호텔은 모든 식사를 준비할 수 있다.','provide'),
                                                                                               ('NORMAL','She loves watching animation movies.','애니메이션','명사','그녀는 애니메이션 영화를 보는 것을 좋아한다.','animation'),
                                                                                               ('NORMAL','Try to imagine a world without any diseases.','상상하다','동사','질병이 전혀 없는 세상을 상상해 보세요.','imagine'),
                                                                                               ('HARD','His imagine was quite vivid.','상상','명사','그의 상상은 꽤 생생했다.','imagine'),
                                                                                               ('HARD','The incorporated company started its operations recently.','통합된','형용사','통합된 회사는 최근에 운영을 시작했다.','incorporate'),
                                                                                               ('NORMAL','We need to incorporate new technologies into our products.','포함하다','동사','우리는 제품에 새로운 기술을 포함시켜야 한다.','incorporate'),
                                                                                               ('HARD','They decided to incorporate their startup.','법인으로 만들다','동사','그들은 그들의 스타트업을 법인으로 만들기로 결정했다.','incorporate'),
                                                                                               ('HARD','Natural language processing is a field of AI.','자연어 처리','명사','자연어 처리는 AI의 한 분야이다.','natural language processing'),
                                                                                               ('NORMAL','The algorithm improved the efficiency of the program.','알고리즘','명사','알고리즘은 프로그램의 효율성을 향상시켰다.','algorithm'),
                                                                                               ('NORMAL','The movie was amazing.','놀라운','형용사','그 영화는 놀라웠다.','amazing');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','Her performance was truly amazing.','경이로운','형용사','그녀의 공연은 정말 경이로웠다.','amazing'),
                                                                                               ('HARD','Machine learning is a subset of artificial intelligence.','기계 학습','명사','기계 학습은 인공지능의 하위 분야이다.','machine learning'),
                                                                                               ('NORMAL','His comments were relevant to the topic.','관련 있는','형용사','그의 발언은 주제와 관련이 있었다.','relevant'),
                                                                                               ('HARD','She effectively managed the team to meet the deadline.','효과적으로','부사','그녀는 팀을 효과적으로 관리하여 마감일을 맞췄다.','effectively'),
                                                                                               ('NORMAL','Scientists explore new areas to discover unknown species.','탐험하다','동사','과학자들은 미지의 종을 발견하기 위해 새로운 지역을 탐험한다.','explore'),
                                                                                               ('HARD','The police explore all possibilities in the investigation.','조사하다','동사','경찰은 조사에서 모든 가능성을 조사한다.','explore'),
                                                                                               ('HARD','Researchers explore various methods to improve the vaccine.','연구하다','동사','연구자들은 백신을 개선하기 위한 다양한 방법을 연구한다.','explore'),
                                                                                               ('NORMAL','This is a paid tool, so you need to purchase it to use it.','유료의','형용사','이것은 유료 도구이므로 사용하려면 구매해야 합니다.','paid tool'),
                                                                                               ('NORMAL','Many professionals use paid tools for their work.','유료 도구','명사','많은 전문가가 그들의 업무를 위해 유료 도구를 사용합니다.','paid tool'),
                                                                                               ('HARD','The company introduced a new service package for its customers.','서비스 패키지','명사','회사는 고객을 위한 새로운 서비스 패키지를 도입했다.','service package');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('EASY','Please provide tools for use.','사용','명사','사용을 위한 도구를 제공해 주세요.','use'),
                                                                                               ('EASY','I use my computer for work.','사용하다','동사','나는 일을 위해 내 컴퓨터를 사용한다.','use'),
                                                                                               ('NORMAL','This equipment has multiple uses.','용도','명사','이 장비는 여러 용도가 있다.','use'),
                                                                                               ('HARD','He used a pole as a leverage to lift the rock.','지렛대','명사','그는 돌을 들어 올리기 위해 막대를 지렛대로 사용했다.','leverage'),
                                                                                               ('NORMAL','She decided to use her skills in writing.','써먹다','동사','그녀는 글쓰기에서 자신의 기술을 써먹기로 했다.','use'),
                                                                                               ('NORMAL','She has a lot of leverage in the company.','영향력','명사','그녀는 회사에서 많은 영향력을 가지고 있다.','leverage'),
                                                                                               ('HARD','We need to leverage our resources better.','활용하다','동사','우리는 우리의 자원을 더 잘 활용할 필요가 있다.','leverage'),
                                                                                               ('HARD','The use of this method is under debate.','효용성','명사','이 방법의 효용성은 논쟁 중이다.','use'),
                                                                                               ('NORMAL','We need to calculate the average cost of materials.','평균 비용','명사','우리는 재료의 평균 비용을 계산해야 한다.','average cost'),
                                                                                               ('NORMAL','I wrote a note to remind myself of the meeting.','필기, 메모','명사','나는 회의를 상기시키기 위해 메모를 작성했다.','note');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','She played a wrong note on the piano.','음표','명사','그녀는 피아노에서 틀린 음표를 연주했다.','note'),
                                                                                               ('HARD','His achievements are worthy of note.','주의, 주목','명사','그의 업적은 주목할 만하다.','note'),
                                                                                               ('HARD','Please note the changes in the schedule.','주목하다, 유념하다','동사','일정 변경 사항을 유념해 주세요.','note'),
                                                                                               ('HARD','The scientist noted the results of the experiment.','기록하다','동사','과학자는 실험 결과를 기록했다.','note'),
                                                                                               ('NORMAL','She received a letter from her friend.','받다','동사','그녀는 친구로부터 편지를 받았다.','receive'),
                                                                                               ('NORMAL','I received the message you sent yesterday.','수신하다','동사','나는 어제 당신이 보낸 메시지를 받았다.','receive'),
                                                                                               ('NORMAL','One interesting feature of this car is its automatic parking system.','특징','명사','이 차의 흥미로운 특징 중 하나는 자동 주차 시스템이다.','feature'),
                                                                                               ('NORMAL','Her features are strikingly beautiful.','이목구비','명사','그녀의 이목구비는 눈에 띄게 아름답다.','feature'),
                                                                                               ('HARD','This magazine will feature the famous artist in its next issue.','특집으로 하다','동사','이 잡지는 다음 호에 유명한 예술가를 특집으로 다룰 것이다.','feature'),
                                                                                               ('NORMAL','The concert features several famous musicians.','포함하다','동사','그 콘서트는 여러 유명한 음악가들을 포함한다.','feature');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','The two words are equivalent in meaning.','동등한, 같은','형용사','두 단어는 의미가 동등하다.','equivalent'),
                                                                                               ('HARD','There is no exact equivalent for this word in Korean.','동등한 것, 대응물','명사','이 단어에 대한 정확한 한국어 대응물이 없다.','equivalent'),
                                                                                               ('HARD','The video editor allows you to cut and merge video clips.','비디오 편집기','명사','비디오 편집기는 동영상 클립을 자르고 합치는 것을 허용한다.','video editor'),
                                                                                               ('NORMAL','He has good credit with the bank.','신용','명사','그는 은행으로부터 좋은 신용을 가지고 있다.','credit'),
                                                                                               ('HARD','She needs three more credits to graduate.','학점','명사','그녀는 졸업하기 위해 3학점이 더 필요하다.','credit'),
                                                                                               ('VERY_HARD','You can credit him with honesty.','믿다','동사','그의 정직함을 믿어도 된다.','credit'),
                                                                                               ('NORMAL','The farmer takes his produce to the market.','농산물','명사','농부는 농산물을 시장으로 가져간다.','produce'),
                                                                                               ('NORMAL','Factories produce goods for consumers.','생산하다','동사','공장은 소비자들을 위한 제품을 생산한다.','produce'),
                                                                                               ('HARD','This artist will produce the film.','제작하다','동사','이 예술가는 그 영화를 제작할 것이다.','produce'),
                                                                                               ('NORMAL','I decided to sign up for the cooking class.','등록하다','동사','나는 요리 수업에 등록하기로 했다.','sign up');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','The comparison between the two products was enlightening.','비교','명사','두 제품 간의 비교는 계몽적이었다.','comparison'),
                                                                                               ('HARD','His comparison of life to a journey was thought-provoking.','비유','명사','그의 삶에 대한 여행의 비유는 많은 생각을 하게 했다.','comparison'),
                                                                                               ('EASY','This software is easy to use.','사용하기 쉬운','형용사','이 소프트웨어는 사용하기 쉽다.','easy to use'),
                                                                                               ('HARD','Please send me the registration link for the event.','등록 링크','명사','행사 등록 링크를 보내주세요.','registration link'),
                                                                                               ('NORMAL','Please fill in your name on the form.','채우다','동사','양식에 이름을 기입해 주세요.','fill in'),
                                                                                               ('HARD','They need to fill in the holes in the road.','메우다','동사','그들은 도로의 구멍을 메워야 한다.','fill in'),
                                                                                               ('NORMAL','The software upgrade improved performance.','업그레이드','명사','소프트웨어 업그레이드가 성능을 향상시켰다.','upgrade'),
                                                                                               ('NORMAL','We need to upgrade our computer system.','업그레이드하다','동사','우리는 컴퓨터 시스템을 업그레이드해야 한다.','upgrade'),
                                                                                               ('NORMAL','The project is completed.','완료된','형용사','프로젝트가 완료되었다.','completed'),
                                                                                               ('HARD','She completed the assignment.','완료하다','동사','그녀는 과제를 완료했다.','completed');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','The user interface of this software is very intuitive.','인터페이스','명사','이 소프트웨어의 사용자 인터페이스는 매우 직관적이다.','interface'),
                                                                                               ('VERY_HARD','The software allows users to interface with the hardware directly.','상호작용하다','동사','이 소프트웨어는 사용자가 하드웨어와 직접 상호작용할 수 있도록 한다.','interface'),
                                                                                               ('NORMAL','She appeared suddenly in the doorway.','나타나다','동사','그녀는 갑자기 문간에 나타났다.','appear'),
                                                                                               ('HARD','It appears that he is telling the truth.','~인 것 같다','동사','그가 진실을 말하는 것 같다.','appear'),
                                                                                               ('EASY','The room was empty.','빈','형용사','방이 비어 있었다.','empty'),
                                                                                               ('NORMAL','Please empty the trash can.','비우다','동사','쓰레기통을 비워 주세요.','empty'),
                                                                                               ('EASY','There was an empty on the street after the parade.','빈 곳','명사','퍼레이드 후 거리에는 빈 곳이 있었다.','empty'),
                                                                                               ('NORMAL','She wants to create a new art piece.','만들다','동사','그녀는 새로운 예술 작품을 만들고 싶어 한다.','create'),
                                                                                               ('HARD','The goal is to create a sustainable environment.','창조하다','동사','목표는 지속 가능한 환경을 창조하는 것이다.','create'),
                                                                                               ('VERY_HARD','Engineers create blueprints for buildings.','설계하다','동사','엔지니어들은 건물의 설계도를 작성한다.','create');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('NORMAL','The team received a lot of support from their fans.','지원','명사','그 팀은 팬들로부터 많은 지원을 받았다.','support'),
                                                                                               ('HARD','The bridge needs additional support to remain stable.','지지대','명사','다리가 안정적으로 유지되기 위해 추가적인 지지대가 필요하다.','support'),
                                                                                               ('NORMAL','We support local businesses by shopping at their stores.','지원하다','동사','우리는 그들의 가게에서 쇼핑함으로써 지역 사업을 지원한다.','support'),
                                                                                               ('NORMAL','She supports the idea of renewable energy.','지지하다','동사','그녀는 재생 에너지의 아이디어를 지지한다.','support'),
                                                                                               ('HARD','The roof is supported by thick wooden beams.','받쳐주다','동사','지붕은 두꺼운 목재 빔으로 받쳐져 있다.','support'),
                                                                                               ('HARD','We visited the ancient section of the museum.','부분, 구역','명사','우리는 박물관의 고대 구역을 방문했다.','section'),
                                                                                               ('NORMAL','Please refer to section 4 of the document.','절, 단락','명사','문서의 4절을 참조해 주세요.','section'),
                                                                                               ('VERY_HARD','The land was sectioned off for development.','분할하다, 나누다','동사','그 땅은 개발을 위해 분할되었다.','section'),
                                                                                               ('NORMAL','The train left the platform at 8:00 AM.','플랫폼, 기반','명사','기차는 오전 8시에 플랫폼을 떠났다.','platform'),
                                                                                               ('HARD','She spoke confidently from the platform.','무대, 연단','명사','그녀는 연단에서 자신 있게 연설했다.','platform');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('NORMAL','The tour guide showed us around the city.','안내자','명사','여행 안내자가 우리에게 도시를 안내했다.','guide'),
                                                                                               ('HARD','I read a guide to learn more about photography.','지침서','명사','나는 사진에 대해 더 배우기 위해 지침서를 읽었다.','guide'),
                                                                                               ('NORMAL','She will guide you through the steps.','안내하다','동사','그녀가 당신을 단계별로 안내할 것이다.','guide'),
                                                                                               ('NORMAL','I bought a travel guide for Europe.','가이드(책자)','명사','나는 유럽에 대한 여행 가이드를 샀다.','guide'),
                                                                                               ('NORMAL','His selection for the position was well-received.','선택','명사','그가 그 직책에 선택된 것은 좋은 반응을 얻었다.','selection'),
                                                                                               ('NORMAL','The selection of candidates took several weeks.','선발','명사','후보자 선발에는 몇 주가 걸렸다.','selection'),
                                                                                               ('HARD','This device can generate electricity.','생성하다','동사','이 장치는 전기를 생성할 수 있다.','generate'),
                                                                                               ('HARD','The movie generated a lot of interest.','일으키다','동사','그 영화는 많은 관심을 일으켰다.','generate'),
                                                                                               ('NORMAL','The program is used to generate reports.','만들다','동사','그 프로그램은 보고서를 만드는 데 사용된다.','generate'),
                                                                                               ('NORMAL','The designer used a template to streamline the creation of new designs.','템플릿','명사','디자이너는 새로운 디자인의 생성을 간편하게 하기 위해 템플릿을 사용했다.','template');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','The letter had a template-like structure, lacking any personal touch.','형식적인','형용사','그 편지는 형식적인 구조를 가지고 있어, 어떤 개인적인 터치도 부족했다.','template'),
                                                                                               ('NORMAL','She reviewed the subscription plan before signing up.','구독 계획','명사','그녀는 가입하기 전에 구독 계획을 검토했다.','subscription plan'),
                                                                                               ('HARD','The outline sketch was used for the painting.','윤곽의','형용사','윤곽 스케치는 그림에 사용되었다.','outline'),
                                                                                               ('NORMAL','He provided an outline of the project.','개요','명사','그는 프로젝트의 개요를 제공했다.','outline'),
                                                                                               ('HARD','She will outline the main ideas in her presentation.','윤곽을 그리다','동사','그녀는 발표에서 주요 아이디어의 윤곽을 그릴 것이다.','outline'),
                                                                                               ('NORMAL','She explained the details of the plan.','세부사항','명사','그녀는 계획의 세부사항을 설명했다.','detail'),
                                                                                               ('HARD','Can you detail what happened?','상술하다','동사','무슨 일이 있었는지 상술해 줄 수 있나요?','detail'),
                                                                                               ('NORMAL','The label on the jar was torn.','라벨, 표','명사','병에 붙어 있는 라벨이 찢어졌다.','label'),
                                                                                               ('HARD','She decided to label the boxes for easy identification.','라벨을 붙이다','동사','그녀는 쉽게 식별할 수 있도록 상자에 라벨을 붙이기로 했다.','label'),
                                                                                               ('HARD','His music is released under a new label.','상표','명사','그의 음악은 새로운 상표로 발매된다.','label');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','They labeled him as a troublemaker.','꼬리표를 붙이다','동사','그들은 그를 말썽꾼이라고 분류했다.','label'),
                                                                                               ('HARD','The promotion of the new product was a great success.','홍보','명사','신제품 홍보가 큰 성공을 거두었다.','promotion'),
                                                                                               ('NORMAL','She received a promotion to manager last year.','승진','명사','그녀는 작년에 매니저로 승진했다.','promotion'),
                                                                                               ('HARD','The company''s promotion of environmental policies gained public approval.','촉진','명사','회사의 환경 정책 촉진은 대중의 지지를 얻었다.','promotion'),
                                                                                               ('NORMAL','Please enter the room quietly.','들어가다','동사','조용히 방에 들어가 주세요.','enter'),
                                                                                               ('NORMAL','Enter your password to log in.','입력하다','동사','로그인하려면 비밀번호를 입력하세요.','enter'),
                                                                                               ('EASY','The main enter is over there.','입구','명사','대문 입구는 저쪽에 있습니다.','enter'),
                                                                                               ('NORMAL','The length of the table is 2 meters.','길이','명사','테이블의 길이는 2미터이다.','length'),
                                                                                               ('HARD','She wore a medium-length dress to the party.','보통 길이의','형용사','그녀는 파티에 보통 길이의 드레스를 입었다.','medium-length'),
                                                                                               ('NORMAL','This is a special occasion.','특별한','형용사','이것은 특별한 자리다.','special');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','He received special consideration.','특혜','명사','그는 특별한 배려를 받았다.','special'),
                                                                                               ('NORMAL','This park is a natural habitat for many species.','자연의','형용사','이 공원은 많은 종의 자연 서식지이다.','natural'),
                                                                                               ('HARD','She has a natural talent for music.','타고난','형용사','그녀는 음악에 타고난 재능이 있다.','natural'),
                                                                                               ('HARD','He has a very natural way of speaking.','꾸밈없는','형용사','그는 매우 꾸밈없이 말한다.','natural'),
                                                                                               ('NORMAL','She was satisfied with the results.','만족하는','형용사','그녀는 결과에 만족했다.','satisfied'),
                                                                                               ('HARD','The explanations satisfied my curiosity.','만족시키다','동사','설명이 내 호기심을 만족시켰다.','satisfied'),
                                                                                               ('NORMAL','It is important to wear appropriate clothing for the event.','적절한','형용사','행사를 위한 적절한 의상을 입는 것이 중요하다.','appropriate'),
                                                                                               ('VERY_HARD','The committee will appropriate funds for the new project.','할당하다 (영국 영어에서 주로 사용)','동사','위원회는 새로운 프로젝트를 위해 자금을 할당할 것이다.','appropriate'),
                                                                                               ('NORMAL','The actor read the script carefully.','대본','명사','배우는 대본을 주의 깊게 읽었다.','script'),
                                                                                               ('HARD','The script on the ancient artifact was difficult to decipher.','문자','명사','고대 유물의 문자는 해독하기 어려웠다.','script');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','Her script was neat and easy to read.','필체','명사','그녀의 필체는 깔끔하고 읽기 쉬웠다.','script'),
                                                                                               ('VERY_HARD','She decided to script her own play.','각본을 쓰다','동사','그녀는 자신의 극의 각본을 쓰기로 결정했다.','script'),
                                                                                               (EXTREME,'He learned to script in Python.','컴퓨터 프로그램을 작성하다','동사','그는 파이썬으로 프로그램을 작성하는 법을 배웠다.','script'),
                                                                                               ('NORMAL','The building has a vertical structure.','수직의','형용사','그 건물은 수직 구조를 가지고 있다.','vertical format'),
                                                                                               ('NORMAL','The vertical lines on the chart represent years.','세로의','형용사','차트의 세로선은 연도를 나타낸다.','vertical format'),
                                                                                               ('HARD','The plane climbed to maintain a vertical position.','수직','명사','비행기는 수직 위치를 유지하기 위해 상승했다.','vertical format'),
                                                                                               ('NORMAL','The transition from summer to autumn is beautiful.','전환','명사','여름에서 가을로의 전환은 아름답다.','transition'),
                                                                                               ('HARD','We need to transition to a new system by next month.','전환하다','동사','우리는 다음 달까지 새로운 시스템으로 전환해야 한다.','transition'),
                                                                                               ('EASY','She came in second place in the race.','두 번째의','형용사','그녀는 경주에서 두 번째로 들어왔다.','second'),
                                                                                               ('EASY','There are sixty seconds in a minute.','초','명사','1분에는 60초가 있다.','second');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','Can you second the timing of the race?','(시간을) 재다','동사','경주의 시간을 재줄 수 있니?','second'),
                                                                                               ('VERY_HARD','This store sells seconds at a discount.','중고품','명사','이 가게는 중고품을 할인가에 판매한다.','second'),
                                                                                               ('HARD','Can I count on you for a second?','도움','명사','너의 도움을 믿어도 될까?','second'),
                                                                                               ('HARD','This dress is suitable for the occasion.','적절한','형용사','이 드레스는 그 행사에 적절하다.','suitable'),
                                                                                               ('NORMAL','You need to select the correct answer.','선택하다','동사','올바른 답을 선택해야 한다.','select'),
                                                                                               ('HARD','They will select a new leader tomorrow.','선출하다','동사','그들은 내일 새로운 지도자를 선출할 것이다.','select'),
                                                                                               ('HARD','Only select guests are invited to the event.','엄선된','형용사','오직 엄선된 손님들만 그 행사에 초대받는다.','select'),
                                                                                               ('EASY','You have a select of different flavors.','선택','명사','다양한 맛을 선택할 수 있다.','select'),
                                                                                               ('HARD','The book includes numerous illustrative examples.','설명적인','형용사','그 책에는 많은 설명적인 예시가 포함되어 있다.','illustrative'),
                                                                                               ('NORMAL','The doors open automatically when you approach.','자동으로','부사','당신이 다가가면 문이 자동으로 열린다.','automatically');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','The company allows you to personalize your account settings.','개인화하다','동사','회사에서는 계정 설정을 개인화할 수 있게 합니다.','personalize'),
                                                                                               ('HARD','He has a dynamic personality.','역동적인','형용사','그는 역동적인 성격을 가지고 있다.','dynamic'),
                                                                                               ('NORMAL','The economy is a dynamic system.','동적인','형용사','경제는 동적인 체계이다.','dynamic'),
                                                                                               ('HARD','She is a dynamic speaker.','활발한','형용사','그녀는 활발한 연설자이다.','dynamic'),
                                                                                               ('VERY_HARD','He is studying the dynamics of flight.','동력학','명사','그는 비행의 동력학을 연구하고 있다.','dynamic'),
                                                                                               ('NORMAL','Her style is quite unique.','독특한','형용사','그녀의 스타일은 꽤 독특하다.','unique'),
                                                                                               ('NORMAL','We need to replace the old computer.','대체하다','동사','우리는 오래된 컴퓨터를 대체해야 한다.','replace'),
                                                                                               ('NORMAL','This is a unique opportunity.','유일한','형용사','이것은 유일한 기회이다.','unique'),
                                                                                               ('NORMAL','I will replace the broken window tomorrow.','교체하다','동사','나는 내일 깨진 창문을 교체할 것이다.','replace'),
                                                                                               ('HARD','The replacement arrived today.','교체품','명사','교체품이 오늘 도착했다.','replace');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('HARD','I need to download the file before I can open it.','다운로드하다','동사','그 파일을 열기 전에 다운로드해야 한다.','download'),
                                                                                               ('NORMAL','The download was very quick.','다운로드','명사','다운로드가 매우 빨랐다.','download'),
                                                                                               ('HARD','I need to upload the files before the deadline.','업로드하다','동사','나는 마감일 전에 파일을 업로드해야 한다.','upload'),
                                                                                               ('HARD','The upload took longer than expected.','업로드','명사','업로드는 예상보다 오래 걸렸다.','upload'),
                                                                                               ('NORMAL','She will edit the document for errors.','수정하다','동사','그녀는 문서의 오류를 수정할 것이다.','edit'),
                                                                                               ('HARD','The final edit of the film took weeks.','편집','명사','영화의 최종 편집에는 몇 주가 걸렸다.','edit'),
                                                                                               ('HARD','I subscribe to several science journals.','구독하다','동사','나는 여러 과학 저널을 구독한다.','subscribe'),
                                                                                               ('VERY_HARD','I cannot subscribe to that point of view.','동의하다','동사','나는 그 견해에 동의할 수 없다.','subscribe'),
                                                                                               ('NORMAL','She was so excited about the concert.','신이 난','형용사','그녀는 콘서트에 대해 매우 신이 났다.','excited'),
                                                                                               ('HARD','The news excited the crowd.','흥분시키다','동사','그 소식은 군중을 흥분시켰다.','excited');
INSERT INTO PUBLIC.WORD (DIFFICULTY,EXAMPLE_SENTENCE,MEANING,POS,TRANSLATED_SENTENCE,WORD) VALUES
                                                                                               ('NORMAL','The country has abundant natural resources.','자원','명사','그 나라는 풍부한 천연 자원을 가지고 있다.','resource'),
                                                                                               ('HARD','She found new resources in herself to overcome the challenge.','수단','명사','그녀는 그 도전을 극복하기 위해 자신 안에서 새로운 수단을 찾았다.','resource'),
                                                                                               ('VERY_HARD','The company resources various projects every year.','자원을 제공하다','동사','그 회사는 매해 다양한 프로젝트에 자원을 제공한다.','resource'),
                                                                                               ('NORMAL','We need to check out the new restaurant in town.','확인하다','동사구','우리는 시내의 새로운 식당을 확인해 봐야 해.','check out'),
                                                                                               ('HARD','He went to the library to check out some books.','대출하다','동사구','그는 책을 대출하기 위해 도서관에 갔다.','check out'),
                                                                                               ('NORMAL','We will check out of the hotel at noon.','나가다','동사구','우리는 정오에 호텔에서 나갈 것이다.','check out'),
                                                                                               ('NORMAL','I heard the notification bell ring.','알림 벨','명사','나는 알림 벨이 울리는 소리를 들었다.','notification bell');